name: moniepoint_test
description: "A test project of moniepoint interview session."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flex_seed_scheme: ^3.4.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_maps_flutter: ^2.9.0
  iconsax_plus: ^1.0.0
  widget_to_marker: ^1.0.6
  countup: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/euclid-circular-a/EuclidCircularARegular.ttf
        - asset: assets/fonts/euclid-circular-a/EuclidCircularAItalic.ttf
          style: italic
        - asset: assets/fonts/euclid-circular-a/EuclidCircularABold.ttf
          style: normal
    - family: EuclidCircularABold
      fonts:
        - asset: assets/fonts/euclid-circular-a/EuclidCircularABold.ttf
        - asset: assets/fonts/euclid-circular-a/EuclidCircularABoldItalic.ttf
          style: italic



